<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fankinsbook</groupId>
        <artifactId>fankins-book</artifactId>
        <version>${revision}</version>
    </parent>

    <groupId>com.fankins.book.oss</groupId>
    <artifactId>fankins-book-oss</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>fankins-book-oss-api</module>
        <module>fankins-book-oss-biz</module>
    </modules>

</project>